# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

stages:
  - stage: Build
    jobs:
      - job: BuildDockerfile
        steps:
          - bash: echo Build

  - stage: TestDeploy
    dependsOn: DevDeploy
    jobs:
      - job: RunTests
        steps:
          - bash: echo test
  
  - stage: DevDeploy
    dependsOn: Build
    jobs:
      - job: RunDockerCompose
        steps:
          - bash: echo DevDeploy
  