# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

stages:
  - stage: BuildDev
    jobs:
      - deployment: DevDeploy
        environment: Dev
      - job: BuildDockerfile
        steps:
          - bash: echo Build
          - task: Docker@2
            inputs:
              containerRegistry: 'dockerhub'
              repository: 'hugovasc/curso-azure-devops'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'

  - stage: TestDeploy
    dependsOn: DevDeploy
    jobs:
      - job: RunTests
        steps:
          - bash: echo test
  
  - stage: DevDeploy
    dependsOn: Build
    jobs:
      - job: RunDockerCompose
        steps:
          - bash: echo DevDeploy

  - stage: BuildProd
    jobs:
      - deployment: DevDeploy
        environment: Prod
      - job: BuildDockerfile
        steps:
          - bash: echo Build
          - task: Docker@2
            inputs:
              containerRegistry: 'dockerhub'
              repository: 'hugovasc/curso-azure-devops'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'